# Generated by Django 3.2.7 on 2021-09-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('measure_unit', models.CharField(choices=[('шт', 'штук'), ('кг', 'киллограм'), ('л', 'литров')], max_length=10, verbose_name='Единица измерения')),
                ('cost', models.PositiveIntegerField(verbose_name='Цена')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Дата последней поставки/отгрузки')),
            ],
        ),
    ]
